spring:
  application:
    name: WordLOL
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wordlol
    username: root
    password: 3033
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: true
  profiles:
    include: oauth

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.adam9e96.WordLOL.dto

server:
  servlet:
    context-path: /
    encoding:
      force-response: true

jwt:
  secret-key: "ThisIsASecureSecretKeyForJwtAuthenticationRequiredMinimum32BytesFor256Bits"
  access-token-validity-in-ms: 3600000
  refresh-token-validity-in-ms: 2592000000

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json