### GET 단어 1개 조회(READ)
GET http://localhost:8080/api/v1/words/30

### PUT 단어 수정(UPDATE)
PUT http://localhost:8080/api/v1/words/30
Content-Type: application/json

{
  "vocabulary": "beach1",
  "meaning": "해변1",
  "difficulty": 3,
  "hint": "해변1"
}

### GET 랜덤 단어 조회
GET http://localhost:8080/api/v1/words/random


### Delete
DELETE http://localhost:8080/api/v1/words/110


### GET hint
GET http://localhost:8080/api/v1/words/28/hint

### POST 정답 확인
POST http://localhost:8080/api/v1/words/check
Content-Type: application/json

{
  "wordId": 30,
  "answer": "해변1"
}

### 연속 정답 확인
GET http://localhost:8080/api/v1/words/perfectRun

### 단어 5개 랜덤 조회
GET http://localhost:8080/api/v1/words/daily-words

### 단어 리스트 조회 with 페이징 정보
GET http://localhost:8080/api/v1/words/list


### 단어 추가
POST http://localhost:8080/api/v1/words/register
Content-Type: application/json

{
  "vocabulary": "test",
  "meaning": "test2meaning",
  "difficulty": 2,
  "hint": "testhint1"
}

### 단어 N개 추가
POST http://localhost:8080/api/v1/words/book
Content-Type: application/json

[
  {
    "vocabulary": "apple",
    "meaning": "사과",
    "hint": "빨간 과일",
    "difficulty": 1
  },
  {
    "vocabulary": "banana",
    "meaning": "바나나",
    "hint": "노란 과일",
    "difficulty": 1
  },
  {
    "vocabulary": "cherry",
    "meaning": "체리",
    "hint": "작고 빨간 과일",
    "difficulty": 2
  }
]
