### WordNotFoundException 관련 API 테스트
### 1. 존재하지 않는 단어 조회 (404 에러)
### getWord() 메소드에서 wordId에 해당하는 단어가 없을 때 발생하는 예외
GET http://localhost:8080/api/v1/words/99999

### 2. 존재하지 않는 단어의 힌트 조회 (404 에러)
### getHint() 메소드에서 wordId에 해당하는 단어가 없을 때 발생하는 예외
GET http://localhost:8080/api/v1/words/99999/hint

### 2. 잘못된 ID로 단어 수정 (404 에러)
PUT http://localhost:8080/api/v1/words/99999
Content-Type: application/json

{
  "vocabulary": "beach1",
  "meaning": "해변1",
  "difficulty": 3,
  "hint": "해변1"
}

### WordCreationException 관련 API 테스트 끝


### WordUpdateException 관련 API 테스트
### 1. 단어 수정 시 유효하지 않은 데이터 (400 에러)
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "",
  "meaning": "바나나",
  "difficulty": 1,
  "hint": "해변1"
}


### 2. 단어 수정 시 유효하지 않은 데이터 (400 에러)
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "banana",
  "meaning": "",
  "difficulty": 1,
  "hint": "해변1"
}


### 3. 단어 수정 시 유효하지 않은 데이터 (400 에러)
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "banana",
  "meaning": "바나나",
  "difficulty": 10,
  "hint": "해변1"
}



### 4. 단어 수정 시 유효하지 않은 데이터 (400 에러)
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "한글",
  "meaning": "바나나",
  "difficulty": 10,
  "hint": "해변1"
}

### 5. 힌트 길이 초과
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "banana",
  "meaning": "바나나",
  "difficulty": 3,
  "hint": "너무 긴 힌트를 입력해서 100자를 초과하는 경우입니다. 이 힌트는 길이 제한을 넘어설 것입니다. 이렇게 길게 작성하면 유효성 검증에서 제한될 것입니다.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}

### 6. 중복 단어 체크
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "banana",
  "meaning": "기존에 등록된 단어",
  "difficulty": 3,
  "hint": "중복 단어 체크"
}

### 7. 특수문자 포함된 단어
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "banana!@#",
  "meaning": "바나나",
  "difficulty": 3,
  "hint": "특수문자 포함"
}