### GET 단어 1개 조회(READ)
### getWord() 메소드에서 wordId에 해당하는 단어 조회
GET http://localhost:8080/api/v1/words/40

### PUT 단어 수정(UPDATE)
PUT http://localhost:8080/api/v1/words/40
Content-Type: application/json

{
  "vocabulary": "beach1",
  "meaning": "해변1",
  "difficulty": 3,
  "hint": "해변1"
}

### GET 랜덤 단어 조회
GET http://localhost:8080/api/v1/words/random


### 단어 삭제 (DELETE) START
DELETE http://localhost:8080/api/v1/words/45

### 단어 삭제 (DELETE) END


### 단어 힌트 조회
### getHint() 메소드에서 wordId에 해당하는 단어의 힌트 조회
GET http://localhost:8080/api/v1/words/40/hint

### POST 정답 확인
POST http://localhost:8080/api/v1/words/check
Content-Type: application/json

{
  "wordId": 30,
  "answer": "해변1"
}

### 연속 정답 확인
GET http://localhost:8080/api/v1/words/perfectRun

### 단어 5개 랜덤 조회
GET http://localhost:8080/api/v1/words/daily-words

### 단어 리스트 조회 with 페이징 정보
GET http://localhost:8080/api/v1/words/list

### 단어 목록 페이징 조회
GET http://localhost:8080/api/v1/words/list?page=0&size=20

### WordCreate 관련 API 테스트 시작 START
### 단어 추가 (CREATE) 200 OK
POST http://localhost:8080/api/v1/words/register
Content-Type: application/json

{
  "vocabulary": "testA",
  "meaning": "test",
  "difficulty": 1,
  "hint": "testhint1"
}


### 빈 힌트로 생성 (200 성공)
POST http://localhost:8080/api/v1/words/register
Content-Type: application/json

{
  "vocabulary": "testB",
  "meaning": "테스트",
  "difficulty": 1,
  "hint": ""
}

### 단어 추가 END

### 단어 N개 추가
POST http://localhost:8080/api/v1/words/registers
Content-Type: application/json

[
  {
    "vocabulary": "apple",
    "meaning": "사과",
    "hint": "빨간 과일",
    "difficulty": 1
  },
  {
    "vocabulary": "banana",
    "meaning": "바나나",
    "hint": "노란 과일",
    "difficulty": 1
  },
  {
    "vocabulary": "cherry",
    "meaning": "체리",
    "hint": "작고 빨간 과일",
    "difficulty": 2
  }
]
